#ifndef __ACKBAR_STATE_H__
#define __ACKBAR_STATE_H__

enum AckbarState
{
  STATE_RESET,
  STATE_ERROR,
  STATE_STARTUP,
  STATE_CALIBRATING,
  STATE_ARMING,
  STATE_ARMED,
  STATE_ACTIVE,
  STATE_LAST
};
  
#endif // __ACKBAR_STATE_H__